#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

AWS_SECRET="$HOME/.aws_secret"
pipenv sync

pipenv run python src/app.py "$AWS_SECRET"

# python src/app.py "$AWS_SECRET"